### ISSUE TITLE
Postfix can't connect to opendkim

### ISSUE THREAD

**Issue by bmccorm2** [instrumentisto/opendkim-docker-image#7]
This is a question more than an issue, but i've just been looking at this same error for too long :)  Postfix refuses to connect to opendkim `fatal: host/service opendkim/8891 not found: Name or service not known`.  Both services are in the same docker network.  Hence, I can go into the container that has postfix installed and do:
```
root@mail:/# telnet opendkim 8891
Trying 192.168.112.4...
Connected to opendkim.
Escape character is '^]'.
```
The only thing i changed in my conf file is the mode:
```
UserID                  opendkim:opendkim
BaseDirectory           /run/opendkim
Socket                  inet:8891

Syslog                  Yes
SyslogSuccess           Yes

Mode                    v
Canonicalization        relaxed/simple


#
# /etc/opendkim/conf.d/10-custom.conf
#
Mode  sv
```

Docker-compose.yml
```
  opendkim:
    image: instrumentisto/opendkim:alpine
    container_name: opendkim
    environment:
      - S6_KILL_GRACETIME:1000
    volumes:
      - /opt/opendkim/default.private:/etc/dkimkeys/dkim.key:ro
      - ./opendkim/10-mode.conf:/etc/opendkim/conf.d/10-mode.conf:ro
      - /etc/localtime:/etc/localtime:ro
```

OpenDKIM is up and running (no errors) and i've already generated my keys and linked them.  

I'm all out of ideas.  Any help would be greatly appreciated.  Thanks!
